     version: '3.7'

services:
  web:
    image: php:7.4-apache
    volumes:
      - /home/umut/FilmFolio/Sourcecode:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: svJxuugBI&
      MYSQL_DATABASE: filmfolio
      MYSQL_USER: umut
      MYSQL_PASSWORD: svJxuugBI&
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
